apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: monitoring

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jaeger
    namespace: monitoring
    labels:
      service: jaeger
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: jaeger
    template:
      metadata:
        labels:
          service: jaeger
      spec:
        imagePullSecrets:
          - name: docker-hub
        containers:
          - name: jaeger
            image: jaegertracing/all-in-one:1.38
            imagePullPolicy: IfNotPresent
            env:
              - name: MEMORY_MAX_TRACES
                value: "100000"
            ports:
              - name: http-ui
                containerPort: 16686
                protocol: TCP
              - name: http-config
                containerPort: 5778
                protocol: TCP
              - name: http-otlpgrpc
                containerPort: 4317
                protocol: TCP
              - name: http-otlp
                containerPort: 4318
                protocol: TCP
              - name: http-proto
                containerPort: 14250
                protocol: TCP
              - name: http-thrift
                containerPort: 14268
                protocol: TCP
              - name: http-metrics
                containerPort: 14269
                protocol: TCP
              - name: http-zipkin
                containerPort: 9411
                protocol: TCP
            resources:
              limits:
                memory: 2048Mi
              requests:
                cpu: 100m
                memory: 1024Mi
        restartPolicy: Always

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: robot-shop
    name: jaeger
    namespace: monitoring
  spec:
    ports:
      - name: http-jaeger
        port: 14250
        targetPort: 14250
      - name: http-ui
        port: 16686
        targetPort: 16686
      - name: http-metrics
        port: 14269
        targetPort: 14269
    selector:
      service: jaeger
