apiVersion: v1
kind: Service
metadata:
  labels:
    app: robot-shop
  name: jaeger
  namespace: monitoring
spec:
  ports:
    - name: http-jaeger
      port: 14250
      targetPort: 14250
    - name: http-ui
      port: 16686
      targetPort: 16686
    - name: http-metrics
      port: 14269
      targetPort: 14269
  selector:
    service: jaeger
