receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: http://jaeger:4317
    tls:
      insecure: true
  prometheus:
    namespace: default
    endpoint: 0.0.0.0:8889

processors:
  assertsprocessor:
    asserts_server:
      endpoint: https://chief.app.dev.asserts.ai/api-server
    asserts_env: dev
    asserts_site: dev
    trace_rate_limit_per_service_per_request: 1
    capture_metrics: true
    custom_attributes:
      "asserts.error.type":
        "default":
          - value_expr: client_errors
            regex: 4..
            source_attributes: ["http.status_code"]
            span_kinds: ["Client", "Server"]
          - value_expr: server_errors
            regex: 5..
            source_attributes: ["http.status_code"]
            span_kinds: ["Client", "Server"]
      "asserts.request.context":
        robot-shop#payment:
          - source_attributes: ["http.url"]
            span_kinds: ["Server"]
            regex: "http://cart:8080(/cart)/anonymous-.*"
          - source_attributes: ["http.url"]
            span_kinds: ["Client"]
            regex: "http://user:8080(/check)/anonymous-.*"
            value_expr: "$$1/<id>"
        robot-shop#shipping:
          - source_attributes: ["http.url"]
            span_kinds: ["Server"]
            regex: "http://cart:8080(/shipping)/anonymous-.*"
        default:
          - source_attributes: ["http.route"]
            regex: "(.+)"
            span_kinds: ["Server"]
          - source_attributes: ["http.url"]
            span_kinds: ["Server"]
            regex: "https?://.+?((/[^/?]+){1,2}).*"
    attributes_as_metric_labels:
      - "rpc.system"
      - "rpc.service"
      - "rpc.method"
      - "aws.table.name"
      - "aws.queue.url"
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [assertsprocessor]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
