# Registry and rpository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: asserts
  cartVersion: "1.0.11"
  catalogueVersion: "1.0.2"
  dispatchVersion: "1.0.3"
  mongodbVersion: "1.0.1"
  loaderVersion: "1.0.1"
  paymentVersion: "1.0.13"
  reportsVersion: "1.0.1"
  ratingsVersion: "1.0.1"
  shippingVersion: "1.0.17"
  userVersion: "1.0.3"
  webVersion: "1.0.2"
  otelcollectorVersion: "v0.0.78"
  pullPolicy: IfNotPresent

# Payment gateway URL
payment:
  gateway: null
  #gateway: https://www.paypal.com
  #gateway: https://www.worldpay.com
  failureHour: 14
  failureFromMinute: 30
  failureTillMinute: 60

shipping:
  failureHour: null
  failureFromMinute: 0
  failureTillMinute: 15

# Pod Security Policy
psp:
  enabled: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

monitor:
  releaseLabel: prometheus
  infraOnly: false

# Storage class to use with redis statefulset.
redis:
  storageClassName: gp3

ocCreateRoute: false

rabbitmq:
  enableExporter: false

tracing:
  enabled: true

otelcollector:
  assertsServer: https://chief.app.dev.asserts.ai/api-server
  assertsEnv: dev
  assertsSite: dev
  tracesPerRequest: 1
