apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongodb
    app: robot-shop
    type: infra
  name: mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  - name: http-metrics
    port: 9216
    targetPort: 9216
  selector:
    service: mongodb
