---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      prometheus:
        namespace: default
        endpoint: 0.0.0.0:8889
      otlp:
        endpoint: http://jaeger.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
      otlp/tempo:
        endpoint: tempo-dev-01-dev-us-central-0.grafana.net:443
        headers:
          authorization: Basic ${env:TEMPO_TOKEN}
      otlp/temposedemo:
        endpoint: tempo-us-central1.grafana.net:443
        headers:
          authorization: Basic ${env:TEMPO_SEDEMO_TOKEN}

    processors:
      assertsprocessor:
        asserts_server:
          endpoint: {{ .Values.otelcollector.assertsServer }}
          user: {{ .Values.otelcollector.assertsUser }}
          password: ${env:ASSERTS_PASSWORD}
        asserts_env: {{ .Values.otelcollector.assertsEnv }}
        asserts_site: {{ .Values.otelcollector.assertsSite }}
        trace_rate_limit_per_service_per_request: {{ .Values.otelcollector.tracesPerRequest }}
        capture_metrics: true
        span_attributes:
          - attr_name: asserts.error.type
            attr_configs:
              - rules:
                  - value_expr: client_errors
                    regex: 4..
                    source_attributes: ["http.status_code"]
                    span_kinds: ["Client", "Server"]
                  - value_expr: server_errors
                    regex: 5..
                    source_attributes: ["http.status_code"]
                    span_kinds: ["Client", "Server"]
          - attr_name: asserts.request.context
            attr_configs:
              - namespace: robot-shop
                service: payment
                rules:
                  - source_attributes: ["http.url"]
                    span_kinds: ["Client"]
                    regex: "http://cart:8080(/cart)/anonymous-.*"
                  - source_attributes: ["http.url"]
                    span_kinds: ["Client"]
                    regex: "http://user:8080(/check)/anonymous-.*"
              - namespace: robot-shop
                service: shipping
                rules:
                  - source_attributes: ["http.url"]
                    span_kinds: ["Client"]
                    regex: "http://cart:8080(/shipping)/anonymous-.*"
              - rules:
                  - source_attributes: ["http.route"]
                    regex: "(.+)"
                    span_kinds: ["Server"]
                  - source_attributes: ["db.operation", "db.name", "net.peer.name", "net.peer.port"]
                    regex: "(.+);(.*);(.+);(.*)"
                    span_kinds: ["Client"]
                    value_expr: $1#$2#$3#$4
                  - source_attributes: ["net.peer.name", "net.peer.port"]
                    regex: (.+);(.*)
                    span_kinds: ["Client"]
                    value_expr: $1#$2
                  - source_attributes: ["http.url"]
                    span_kinds: ["Client", "Server"]
                    regex: "https?://.+?((/[^/?]+){1,2}).*"
        attributes_as_metric_labels:
          - "rpc.system"
          - "rpc.service"
          - "rpc.method"
          - "aws.table.name"
          - "aws.queue.url"
          - "db.system"
          - "db.name"
          - "db.operation"
      groupbytrace:
        wait_duration: 10s
        num_traces: 1000
        num_workers: 1
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [groupbytrace, assertsprocessor]
          exporters: [otlp, otlp/tempo, otlp/temposedemo]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          exporters: [otlp]
