---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      prometheus:
        namespace: default
        endpoint: 0.0.0.0:8889
      otlp:
        endpoint: http://jaeger.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

    processors:
      assertsprocessor:
        asserts_server:
          endpoint: {{ .Values.otelcollector.assertsServer }}
          user: {{ .Values.otelcollector.assertsUser }}
          password: {{ .Values.otelcollector.assertsPassword }}
        asserts_env: {{ .Values.otelcollector.assertsEnv }}
        asserts_site: {{ .Values.otelcollector.assertsSite }}
        trace_rate_limit_per_service_per_request: {{ .Values.otelcollector.tracesPerRequest }}
        capture_metrics: true
        error_type_config:
           http.status_code:
            - error_type: client_errors
              value_match_regex: 4..
            - error_type: server_errors
              value_match_regex: 5..
        request_context_regex:
          robot-shop#payment:
            - attr_name: "http.url"
              span_kind: "Server"
              regex: "http://cart:8080(/cart)/anonymous-.*"
            - attr_name: "http.url"
              span_kind: "Server"
              regex: "http://user:8080(/check)/anonymous-.*"
          robot-shop#shipping:
            - attr_name: "http.url"
              span_kind: "Server"
              regex: "http://cart:8080(/shipping)/anonymous-.*"
          default:
            - attr_name: "http.route"
              span_kind: "Server"
              regex: "(.+)"
            - attr_name: "http.url"
              span_kind: "Server"
              regex: "https?://.+?((/[^/?]+){1,2}).*"
        attributes_as_metric_labels:
          - "rpc.system"
          - "rpc.service"
          - "rpc.method"
          - "aws.table.name"
          - "aws.queue.url"
          - "db.system"
          - "db.name"
          - "db.operation"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [assertsprocessor]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          exporters: [otlp]
