apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: rabbitmq
        image: rabbitmq:3.10.6-management-alpine
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: tcp-amqp
          containerPort: 5672
        - name: tcp-epmd
          containerPort: 4369
        - name: http-management
          containerPort: 15672
        - name: http-metrics
          containerPort: 15692
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        {{- if .Values.rabbitmq.enableExporter }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo [rabbitmq_management,rabbitmq_prometheus]. > /etc/rabbitmq/enabled_plugins"]
        {{- end }}
      restartPolicy: Always
