apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
    app: robot-shop
    type: infra
  name: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: http-metrics
    port: 9121
    targetPort: 9121
  selector:
    service: redis
