---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics
  labels:
    release: {{ .Values.monitor.releaseLabel }}
    app: robot-shop
spec:
  selector:
    matchLabels:
      app: robot-shop
      {{- if .Values.monitor.infraOnly }}
      type: infra
      {{- end }}
  namespaceSelector:
    matchNames:
     - {{ .Release.Namespace }}
  endpoints:
    - port: http
    - port: http-metrics
