apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    service: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      imagePullSecrets:
        - name: docker-hub      
      containers:
      - name: web
        image: {{ .Values.image.repo }}/robot-shop-rs-web:{{ .Values.image.webVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - '-nginx.scrape-uri=http://localhost:8080/nginx_status'
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
          - name: http-metrics
            containerPort: 9113
      restartPolicy: Always
