apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
    app: robot-shop
    type: infra
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: http-metrics
    port: 9113
    targetPort: 9113
  selector:
    service: web
---
{{if .Values.ocCreateRoute}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web
spec:
  to:
    kind: Service
    name: web
{{end}}